DELETE FROM status;
INSERT INTO status VALUES ('IN_STOCK');
INSERT INTO status VALUES ('OUT_OF_STOCK');

INSERT INTO status VALUES ('NEW');
INSERT INTO status VALUES ('IN_PROCESS');
INSERT INTO status VALUES ('PARTIALLY_COMPLETED');
INSERT INTO status VALUES ('COMPLETED');
INSERT INTO status VALUES ('CANCELLED');

INSERT INTO status VALUES ('NEW');
INSERT INTO status VALUES ('PENDING');
INSERT INTO status VALUES ('COMPLETED');
INSERT INTO status VALUES ('CANCELLED');

