DROP TABLE IF EXISTS request;
DROP TABLE IF EXISTS orderitem;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS bookCopy;
DROP TABLE IF EXISTS book;
DROP TABLE IF EXISTS status;
DROP TABLE IF EXISTS stoсk;
