DELETE FROM status;
INSERT INTO status VALUES ('IN_STOCK');
INSERT INTO status VALUES ('OUT_OF_STOCK');
INSERT INTO status VALUES ('NEW');
INSERT INTO status VALUES ('IN_PROCESS');
INSERT INTO status VALUES ('PARTIALLY_COMPLETED');
INSERT INTO status VALUES ('COMPLETED');
INSERT INTO status VALUES ('CANCELLED');
INSERT INTO status VALUES ('PENDING');

DELETE FROM book;
INSERT INTO book VALUES (1,'Last day of summer','dr.Braun','OUT_OF_STOCK',250);
INSERT INTO book VALUES (2,'Last day of winter','dr.Braun','OUT_OF_STOCK',250);
INSERT INTO book VALUES (3,'Sun','Lui Steff','OUT_OF_STOCK',250);

